backend:
  name: github
  branch: wasworking
  repo: GiovanniFerrara/CMS-netlify
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    editor: 
      preview: false 
    slug: "{{year}}-{{month}}-{{day}}-{{}}_{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "cover", name: "cover", widget: image}
      - {label: "author", name: "author", widget: "string"}
      - {label: "body", name: "body", widget: markdown}
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    editor: 
      preview: false 
    slug: "{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Menu Title", name: "menuTitle", widget: "string"}
      - {label: "body", name: "body", widget: markdown}
  # - name: "homepage"
  #   label: Homepage settings
  #   files:
  #     - file: src/content/homepage/homepage.md
  #       name: homepage
  #       label: Homepage settings
  #       delete: false
  #       editor: 
  #         preview: false 
  #       fields:
          # - name: background
          #   label: Background
          #   widget: list
          #   fields:
          #     - label: Background Color
          #       name: color
          #       widget: object
          #       fields: 
          #         - {label: "Primary", name: "primary", required: "false", default: "#ffffff", widget: "color"}
          #         - {label: "Alternative", name: "alt", required: "false", default: "#fafaf9", widget: "color"}
          #         - {label: "Brand", name: "brand", required: "false", default: "#fafaf9", widget: "color"}
          # - name: text
          #   label: Text Options
          #   widget: list
          #   create: "false"
          #   fields:
          #     - label: Family Font
          #       test: family
          #       widget: "string"
          #       required: "false"
          #       default: "Open Sans"
          #     - label: Color
          #       name: color
          #       widget: object
          #       fields: 
          #         - {label: "Primary", name: "primary", required: "false", default: "#709425", widget: "color"}
          #         - {label: "Primary Inverse", name: "primaryInverse", required: "false", default: "#3e3e3c", widget: "color"}
          #         - {label: "Brand", name: "brand", required: "false", default: "#fafaf9", widget: "color"}
                  
  - name: "homepage"
    label: Homepage settings
    files:
      - file: src/content/homepage/homepage.md
        name: homepage
        label: Homepage Settings
        delete: false
        editor: 
          preview: false 
        fields:
          - name: coverDesktop
            label: Cover Picture - Desktop size
            delete: false
            widget: image
          - name: coverTablet
            label: Cover Picture - Tablet size
            delete: false
            widget: image
          - name: coverMobile
            label: Cover Picture - Mobile size
            delete: false
            widget: image