backend:
  name: github
  branch: master
  repo: GiovanniFerrara/CMS-netlify
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    editor: 
      preview: false 
    slug: "{{year}}-{{month}}-{{day}}-{{}}_{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "cover", name: "cover", widget: image}
      - {label: "author", name: "author", widget: "string"}
      - {label: "body", name: "body", widget: markdown}