backend:
  name: github
  branch: master
  repo: GiovanniFerrara/CMS-netlify
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    editor: 
      preview: false 
    slug: "{{year}}-{{month}}-{{day}}-{{}}_{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "cover", name: "cover", widget: image}
      - {label: "author", name: "author", widget: "string"}
      - {label: "body", name: "body", widget: markdown}
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    editor: 
      preview: false 
    slug: "{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Menu Title", name: "menuTitle", widget: "string"}
      - {label: "body", name: "body", widget: markdown}
  - name: "homepage"
    label: Homepage settings
    files:
      - file: src/content/homepage/homepage.md
        name: homepage
        label: Homepage settings
        delete: false
        editor: 
          preview: false 
        fields:
          - name: coverDesktop
            label: Cover Picture - Desktop size
            delete: false
            widget: image
          - name: coverTablet
            label: Cover Picture - Tablet size
            delete: false
            widget: image
          - name: coverMobile
            label: Cover Picture - Mobile size
            delete: false
            widget: image